### ISSUE TITLE
Hello! Juveria

### ISSUE THREAD

**Issue by Tojimurodovsardor25** [JuveriaD/Vanilla-JS#1]
Hello! My name is Sardor : )

**Comment by JuveriaD** [comment]
Did I opened the issue here?🤔🙃

**Comment by Juveria-Dalvi** [comment]
🤔

**Comment by Tojimurodovsardor25** [comment]
Sorry, but we expected the same answer from you 🙂 Good luck...

вт, 2 нояб. 2021 г., 15:19 DJ ***@***.***>:

**Comment by Juveria-Dalvi** [comment]
Which answer? Did I do something 🥲?

**Comment by Tojimurodovsardor25** [comment]
Didn't I disturb you?

**Comment by Juveria-Dalvi** [comment]
No 🙃 but you have created the issue and I'm new over here I don't know what that means !?

**Comment by Tojimurodovsardor25** [comment]
I’m just as new here as you are, but this place is designed to work together on different projects : ) . And there are so many conveniences to it. Excuse me, I want to communicate with you to share ideas and experiences, what do you say? Don’t get me wrong, I’m a future programmer like you and the first person I met on github was you : )

**Comment by Juveria-Dalvi** [comment]
We can get it touch on slack community of [frontendmentor.com](https://www.frontendmentor.io/slack) I do practice a lot over there and that is the only group on slack that help's a lot.. you should try to get there by the site I have mentioned and you'll get lot of collaboration partner over there, once you join let me know by mentioning @DJ in the #introduction so that I'll find you easily over there and also you'll have a lot of help by just asking randomly on #help
See you there🙃

**Comment by Tojimurodovsardor25** [comment]
Thank you! Juveria

**Comment by Juveria-Dalvi** [comment]
See you there👍🏻🎉

**Comment by Tojimurodovsardor25** [comment]
https://www.frontendmentor.io/profile/Tojimurodovsardor25
You can find me via the link, @dj I couldn't search for this username : (

**Comment by Juveria-Dalvi** [comment]
Give your introduction on slack community and it's in upper case @DJ
You'll see the same profile 
[My Front end mentor profile](https://www.frontendmentor.io/profile/JuveriaD)

**Comment by Tojimurodovsardor25** [comment]
I found you:) I really liked the site

**Comment by Tojimurodovsardor25** [comment]
What programming languages ​​do you know?

**Comment by Juveria-Dalvi** [comment]
Great see you on slack 
And I'm learning JavaScript 
I'm absolute begginer

**Comment by Tojimurodovsardor25** [comment]
Glad :) but what a wonderful day you talked about? I couldn't understand you...

**Comment by Juveria-Dalvi** [comment]
Go to the site I mentioned earlier and you'll see at the footer there is a option named "slack" enter your email there then you'll the a link on your mail to join the community of front end mentor

**Comment by Tojimurodovsardor25** [comment]
When I registered, I joined the "Slack" team via this link

**Comment by Tojimurodovsardor25** [comment]
Nice to meet you :) See you in juveria

**Comment by Juveria-Dalvi** [comment]
Did you introduce yourself there?

**Comment by Tojimurodovsardor25** [comment]
This program is very complex, Juveria is how I introduce myself?

**Comment by Juveria-Dalvi** [comment]
Just say hii over there on slack in #introduction
